SELECT USER FROM DUAL;

--create departme
CREATE TABLE departme(
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,
    location VARCHAR2(100),
    CONSTRAINT pk_departments PRIMARY KEY(department_id),
    CONSTRAINT uq_department_name UNIQUE (department_name)
);

--insert departme
INSERT INTO departme (department_name, location)
VALUES ('Cardiology', 'Block A');

INSERT INTO departme (department_name, location)
VALUES ('Neurology', 'Block B');

INSERT INTO departme (department_name, location)
VALUES ('Orthopedics', 'Block C');

INSERT INTO departme (department_name, location)
VALUES ('General Medicine', 'Block A');

INSERT INTO departme (department_name, location)
VALUES ('Pediatrics', 'Block D');

INSERT INTO departme (department_name, location)
VALUES ('Dermatology', 'Block B');

COMMIT;


SELECT * FROM departme;

--create doctor

CREATE TABLE doctor (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    doctor_name VARCHAR2(100) NOT NULL,
    specialization VARCHAR2(100) NOT NULL,
    phone VARCHAR2(15),
    email VARCHAR2(100),
    department_id NUMBER NOT NULL,

    CONSTRAINT pk_doctors PRIMARY KEY (doctor_id),

    CONSTRAINT fk_doctor_department
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
);

--insert doct

INSERT INTO docto
(doctor_name, specialization, phone, email, department_id)
VALUES
('Dr. Ravi Kumar', 'Cardiologist', '9876543210',
 'ravi@hospital.com', 1);

INSERT INTO docto
(doctor_name, specialization, phone, email, department_id)
VALUES
('Dr. Priya Sharma', 'Neurologist', '9876543211',
 'priya@hospital.com', 2);

INSERT INTO docto
(doctor_name, specialization, phone, email, department_id)
VALUES
('Dr. Arjun Rao', 'Orthopedic Surgeon', '9876543212',
 'arjun@hospital.com', 3);

INSERT INTO docto
(doctor_name, specialization, phone, email, department_id)
VALUES
('Dr. Sneha Reddy', 'General Physician', '9876543213',
 'sneha@hospital.com', 4);

INSERT INTO docto
(doctor_name, specialization, phone, email, department_id)
VALUES
('Dr. Kiran Kumar', 'Pediatrician', '9876543214',
 'kiran@hospital.com', 5);

INSERT INTO docto
(doctor_name, specialization, phone, email, department_id)
VALUES
('Dr. Anjali Rao', 'Dermatologist', '9876543215',
 'anjali@hospital.com', 6);

COMMIT;

SELECT * FROM doct;